// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyitj_RzAL171yCkS_UrRIeu5owPIglA',
    appId: '1:354910518833:web:b4a2ae6323749cb6d55f10',
    messagingSenderId: '354910518833',
    projectId: 'prokids-634d9',
    authDomain: 'prokids-634d9.firebaseapp.com',
    storageBucket: 'prokids-634d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNh6rXpne9ej77dsnUFcBb-x_8Eihh9E',
    appId: '1:354910518833:android:d4b1f382c7774fc8d55f10',
    messagingSenderId: '354910518833',
    projectId: 'prokids-634d9',
    storageBucket: 'prokids-634d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwzjZ5t2C1pq9Da0rzHpUB9x-hJidj6So',
    appId: '1:354910518833:ios:d4fdca97ccdfff95d55f10',
    messagingSenderId: '354910518833',
    projectId: 'prokids-634d9',
    storageBucket: 'prokids-634d9.firebasestorage.app',
    iosClientId: '354910518833-ruciv7majl1d172phj3r60tis5iqclck.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwzjZ5t2C1pq9Da0rzHpUB9x-hJidj6So',
    appId: '1:354910518833:ios:d4fdca97ccdfff95d55f10',
    messagingSenderId: '354910518833',
    projectId: 'prokids-634d9',
    storageBucket: 'prokids-634d9.firebasestorage.app',
    iosClientId: '354910518833-ruciv7majl1d172phj3r60tis5iqclck.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmyitj_RzAL171yCkS_UrRIeu5owPIglA',
    appId: '1:354910518833:web:941fb893d0a9fbded55f10',
    messagingSenderId: '354910518833',
    projectId: 'prokids-634d9',
    authDomain: 'prokids-634d9.firebaseapp.com',
    storageBucket: 'prokids-634d9.firebasestorage.app',
  );
}
